// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update
export const KIMI_CODING_MODELS = {
    "k2p7": {
        id: "k2p7",
        name: "Kimi K2.7 Code",
        api: "anthropic-messages",
        provider: "kimi-coding",
        baseUrl: "https://api.kimi.com/coding",
        headers: { "User-Agent": "KimiCLI/1.5" },
        reasoning: true,
        input: ["text", "image"],
        cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
        },
        contextWindow: 262144,
        maxTokens: 32768,
    },
    "kimi-for-coding": {
        id: "kimi-for-coding",
        name: "Kimi For Coding",
        api: "anthropic-messages",
        provider: "kimi-coding",
        baseUrl: "https://api.kimi.com/coding",
        headers: { "User-Agent": "KimiCLI/1.5" },
        reasoning: true,
        input: ["text", "image"],
        cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
        },
        contextWindow: 262144,
        maxTokens: 32768,
    },
    "kimi-k2-thinking": {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        api: "anthropic-messages",
        provider: "kimi-coding",
        baseUrl: "https://api.kimi.com/coding",
        headers: { "User-Agent": "KimiCLI/1.5" },
        reasoning: true,
        input: ["text"],
        cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
        },
        contextWindow: 262144,
        maxTokens: 32768,
    },
};
//# sourceMappingURL=kimi-coding.models.js.map