#![allow(clippy::enum_variant_names)]
use std::borrow::Cow;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::LazyLock;

use convert_case::{Case, Casing};
use derive_more::From;
use eserde::Deserialize;
use forge_tool_macros::ToolDescription;
use schemars::{JsonSchema, Schema};
use serde::Serialize;
use serde_json::Map;
use strum::IntoEnumIterator;
use strum_macros::{AsRefStr, Display, EnumDiscriminants, EnumIter};

use crate::{ToolCallArguments, ToolCallFull, ToolDefinition, ToolDescription, ToolName};

/// Enum representing all possible tool input types.
///
/// This enum contains variants for each type of input that can be passed to
/// tools in the application. Each variant corresponds to the input type for a
/// specific tool.
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    JsonSchema,
    From,
    EnumIter,
    Display,
    PartialEq,
    EnumDiscriminants,
)]
#[strum_discriminants(derive(Display, Serialize, Deserialize, Hash))]
#[strum_discriminants(serde(rename_all = "snake_case"))]
#[serde(tag = "name", content = "arguments", rename_all = "snake_case")]
#[strum_discriminants(name(ToolKind))]
#[strum(serialize_all = "snake_case")]
pub enum ToolCatalog {
    #[serde(alias = "Read")]
    Read(FSRead),
    #[serde(alias = "Write")]
    Write(FSWrite),
    FsSearch(FSSearch),
    SemSearch(SemanticSearch),
    Remove(FSRemove),
    Patch(FSPatch),
    MultiPatch(FSMultiPatch),
    Undo(FSUndo),
    Shell(Shell),
    Fetch(NetFetch),
    Followup(Followup),
    Plan(PlanCreate),
    Skill(SkillFetch),
    TodoWrite(TodoWrite),
    TodoRead(TodoRead),
    #[serde(alias = "Task")]
    Task(TaskInput),
}

/// Input structure for agent tool calls. This serves as the generic schema
/// for dynamically registered agent tools, allowing users to specify tasks
/// for specific agents.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct AgentInput {
    /// A list of clear and detailed descriptions of the tasks to be performed
    /// by the agent in parallel. Provide sufficient context and specific
    /// requirements to enable the agent to understand and execute the work
    /// accurately.
    pub tasks: Vec<String>,
}

/// Input structure for the Task tool - delegates work to specialized agents
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/task.md"]
pub struct TaskInput {
    /// A list of clear and detailed descriptions of the tasks to be performed
    /// by the agent in parallel. Provide sufficient context and specific
    /// requirements to enable the agent to understand and execute the work
    /// accurately.
    pub tasks: Vec<String>,

    /// The ID of the specialized agent to delegate to (e.g., "forge", "muse",
    /// "sage")
    pub agent_id: String,

    /// Optional session ID to continue an existing agent session. If not
    /// provided, a new stateless session will be created. Use this to
    /// maintain context across multiple task invocations with the same
    /// agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

fn default_true() -> bool {
    true
}

/// Status of a todo item
#[derive(
    Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Display, AsRefStr, EnumIter, Default,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum TodoStatus {
    /// Task is pending and not yet started
    #[default]
    Pending,
    /// Task is currently in progress
    InProgress,
    /// Task has been completed
    Completed,
    /// Task is cancelled and should be removed from the list
    Cancelled,
}

impl JsonSchema for TodoStatus {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

/// A todo item
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, derive_setters::Setters)]
#[setters(strip_option, into)]
pub struct Todo {
    /// Unique identifier for the todo item
    pub id: String,
    /// Content/description of the todo item
    pub content: String,
    /// Current status of the todo
    pub status: TodoStatus,
}

impl Todo {
    /// Creates a new todo with the given content
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            id: String::new(), // Will be generated by service if empty
            content: content.into(),
            status: TodoStatus::default(),
        }
    }

    /// Creates a test fixture todo
    #[cfg(test)]
    pub fn test() -> Self {
        Self {
            id: "test-id".to_string(),
            content: "test content".to_string(),
            status: TodoStatus::default(),
        }
    }

    /// Validates the todo item
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - Content is empty
    /// - Content exceeds maximum length (1000 characters)
    pub fn validate(&self) -> anyhow::Result<()> {
        if self.content.trim().is_empty() {
            anyhow::bail!("Todo content cannot be empty");
        }

        if self.content.len() > 1000 {
            anyhow::bail!("Todo content exceeds maximum length of 1000 characters");
        }

        Ok(())
    }

    /// Checks if the todo is completed
    pub fn is_completed(&self) -> bool {
        self.status == TodoStatus::Completed
    }

    /// Checks if the todo is incomplete (pending or in progress)
    pub fn is_incomplete(&self) -> bool {
        matches!(self.status, TodoStatus::Pending | TodoStatus::InProgress)
    }
}

/// Optional line range for partial file reads.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[schemars(deny_unknown_fields)]
pub struct FSReadRange {
    /// 1-based first line.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_line: Option<i32>,

    /// Inclusive 1-based last line.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_line: Option<i32>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_read.md"]
#[schemars(deny_unknown_fields)]
pub struct FSRead {
    /// Absolute path to the file to read.
    #[serde(alias = "path")]
    pub file_path: String,

    /// Optional line range for partial reads.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub range: Option<FSReadRange>,

    /// If true, prefixes each line with its line index (starting at 1).
    /// Defaults to true.
    #[serde(default = "default_true")]
    pub show_line_numbers: bool,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_write.md"]
pub struct FSWrite {
    /// The absolute path to the file to write (must be absolute, not relative)
    #[serde(alias = "path")]
    pub file_path: String,

    /// The content to write to the file
    pub content: String,

    /// If set to true, existing files will be overwritten. If not set and the
    /// file exists, an error will be returned with the content of the
    /// existing file.
    #[serde(default)]
    #[serde(skip_serializing_if = "is_default")]
    pub overwrite: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_search.md"]
#[derive(Default)]
pub struct FSSearch {
    /// The regular expression pattern to search for in file contents.
    pub pattern: String,

    /// File or directory to search in (rg PATH). Defaults to current working
    /// directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Glob pattern to filter files (e.g. "*.js", "*.{ts,tsx}") - maps to rg
    /// --glob
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,

    /// Output mode: "content" shows matching lines (supports -A/-B/-C context,
    /// -n line numbers, head_limit), "files_with_matches" shows file paths
    /// (supports head_limit), "count" shows match counts (supports head_limit).
    /// Defaults to "files_with_matches".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_mode: Option<OutputMode>,

    /// Number of lines to show before each match (rg -B). Requires output_mode:
    /// "content", ignored otherwise.
    #[serde(rename = "-B", skip_serializing_if = "Option::is_none")]
    pub before_context: Option<u32>,

    /// Number of lines to show after each match (rg -A). Requires output_mode:
    /// "content", ignored otherwise.
    #[serde(rename = "-A", skip_serializing_if = "Option::is_none")]
    pub after_context: Option<u32>,

    /// Number of lines to show before and after each match (rg -C). Requires
    /// output_mode: "content", ignored otherwise.
    #[serde(rename = "-C", skip_serializing_if = "Option::is_none")]
    pub context: Option<u32>,

    /// Show line numbers in output (rg -n). Requires output_mode: "content",
    /// ignored otherwise.
    #[serde(rename = "-n", skip_serializing_if = "Option::is_none")]
    pub show_line_numbers: Option<bool>,

    /// Case insensitive search (rg -i)
    #[serde(rename = "-i", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,

    /// File type to search (rg --type). Common types: js, py, rust, go, java,
    /// etc. More efficient than include for standard file types.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub file_type: Option<String>,

    /// Limit output to first N lines/entries, equivalent to "| head -N". Works
    /// across all output modes: content (limits output lines),
    /// files_with_matches (limits file paths), count (limits count entries).
    /// When unspecified, shows all results from ripgrep.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub head_limit: Option<u32>,

    /// Skip first N lines/entries before applying head_limit
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<u32>,

    /// Enable multiline mode where . matches newlines and patterns can span
    /// lines (rg -U --multiline-dotall). Default: false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multiline: Option<bool>,
}

/// Output mode for search results
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, AsRefStr, EnumIter)]
#[serde(rename_all = "snake_case")]
pub enum OutputMode {
    /// Show matching lines with content
    Content,
    /// Show only file paths with matches
    FilesWithMatches,
    /// Show match counts per file
    Count,
}

/// A paired query and use_case for semantic search. Each query must have a
/// corresponding use_case for document reranking.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
pub struct SearchQuery {
    /// The semantic embedding query that describes WHAT the code does or its
    /// purpose. This query is converted to a vector embedding and used to find
    /// semantically similar code chunks in the vector database.
    ///
    /// **Guidelines for effective embedding queries:**
    /// - Use specific, targeted technical terms and domain concepts
    /// - Describe behavior, functionality, patterns, or implementation approach
    /// - Include concrete keywords like technology names, algorithms, data
    ///   structures
    /// - Balance specificity (focused results) with generality (avoid missing
    ///   relevant code)
    /// - Keep queries focused - overly broad queries cause timeouts and poor
    ///   results
    /// - **Align keywords with intent**: For documentation, use "README",
    ///   "guide", "setup"; for implementation, use "function", "logic",
    ///   "handler"
    ///
    /// **Good examples:**
    /// - "exponential backoff retry mechanism with configurable delays"
    /// - "streaming LLM responses with SSE chunked transfer encoding"
    /// - "OAuth2 token refresh with automatic retry and expiry check"
    /// - "Diesel database migration runner with transaction support"
    /// - "semantic search reranker using cross-encoder model"
    /// - "README documentation configuration setup semantic search"
    /// - "markdown guide API documentation tool definitions"
    ///
    /// **Bad examples:**
    /// - "retry" (too generic, will match everything)
    /// - "authentication" (overly broad - specify what aspect: login, tokens,
    ///   middleware?)
    /// - "tool definitions schemas" (too vague - be more specific about
    ///   structure or location)
    /// - "how system works" (meta-question, not searchable concept)
    /// - "function that validates" (focus on what it validates, not that it's a
    ///   function)
    pub query: String,

    /// The reranking query that describes your INTENT and WHY you need this
    /// code. This query is used by the reranker model to filter and
    /// prioritize the most relevant results from the initial embedding
    /// search based on your specific use case.
    ///
    /// **Purpose:** While `query` casts a wide net for similar code, `use_case`
    /// narrows it down by intent: implementation vs docs vs tests, reading
    /// vs modifying code, understanding architecture vs finding bugs, etc.
    ///
    /// **Guidelines for effective reranking queries:**
    /// - **MANDATORY FOR CODE**: ALWAYS include codebase construct keywords
    ///   (struct, trait, impl, interface, class, function, fn, definition,
    ///   implementation, declaration, type) when searching for code
    /// - **WHY CRITICAL**: The reranker gives HIGH WEIGHTAGE to these keywords
    ///   - "struct" → prioritizes struct definitions
    ///   - "trait impl" → prioritizes trait implementations
    ///   - "function" / "fn" → prioritizes function definitions
    ///   - Without these, you get documentation instead of code!
    /// - Clearly state your goal: understand, modify, debug, find examples,
    ///   etc.
    /// - Specify the TYPE of code you need: implementation, tests, docs,
    ///   config, architecture
    /// - Include WHY context: "to fix a bug", "to add a feature", "to
    ///   understand flow"
    /// - Be explicit about what to AVOID: "not tests", "not documentation",
    ///   "not examples"
    /// - **Match intent to file types**: documentation intent → avoid
    ///   requesting "implementation code"; implementation intent → avoid
    ///   requesting "documentation"
    /// - Keep it concise (1-2 sentences) but informative
    /// - MUST be different from the embedding query - add intent/context
    ///
    /// **Good examples (ALWAYS include construct keywords):**
    /// - "I need the struct definition and trait implementation for Diesel
    ///   migrations to understand the transaction handling, not setup docs"
    /// - "Show me the function implementation for semantic search reranker so I
    ///   can modify it to support file type filtering"
    /// - "Find the type declarations and interface definitions for the tool
    ///   registry, not the usage examples"
    /// - "I'm debugging a timeout issue and need the function implementation
    ///   that handles streaming responses, not the API documentation"
    /// - "Show me the struct definitions and trait implementations for
    ///   authentication, not the setup guide"
    /// - "I need the impl block for workspace sync to understand how it detects
    ///   file changes"
    /// - "Find the fn definitions for embedding generation batching logic"
    /// - "I need documentation explaining how to configure semantic search, not
    ///   the implementation code"
    /// - "Find the README or setup guide that explains the tool registration
    ///   process, avoiding implementation details"
    ///
    /// **Bad examples (missing construct keywords = FAILS):**
    /// - "I need code that handles authentication" ❌ MISSING:
    ///   struct/trait/impl/function
    /// - "Show me the database logic" ❌ MISSING: trait/impl/function keywords
    /// - "I need the workspace sync implementation" ❌ MISSING: struct/impl/fn
    ///   - too generic
    /// - "Find the reranker code" ❌ MISSING: struct/trait/impl/function
    /// - "exponential backoff retry mechanism" ❌ MISSING: WHY + construct
    ///   keywords
    /// - "find authentication code" ❌ MISSING: which construct? struct? trait?
    ///   impl?
    /// - "tool definitions" ❌ MISSING: struct? trait? type? be specific
    /// - "how it works" (too vague - specify what you want to understand)
    /// - Long rambling explanation without clear intent (keep it focused)
    pub use_case: String,
}

impl SearchQuery {
    /// Creates a new search query with the given query and use_case
    pub fn new(query: impl Into<String>, use_case: impl Into<String>) -> Self {
        Self { query: query.into(), use_case: use_case.into() }
    }
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/semantic_search.md"]
pub struct SemanticSearch {
    /// List of search queries to execute in parallel. Using multiple queries
    /// (2-3) with varied phrasings significantly improves results - each query
    /// captures different aspects of what you're looking for. Each query pairs
    /// a search term with a use_case for reranking. Example: for
    /// authentication, try "user login verification", "token generation",
    /// "OAuth flow".
    pub queries: Vec<SearchQuery>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_remove.md"]
pub struct FSRemove {
    /// The path of the file to remove (absolute path required)
    pub path: String,
}

/// Operation types that can be performed on matched text
#[derive(Default, Debug, Clone, Serialize, Deserialize, PartialEq, AsRefStr, EnumIter)]
#[serde(rename_all = "snake_case")]
pub enum PatchOperation {
    /// Prepend content before the matched text
    #[default]
    Prepend,

    /// Append content after the matched text
    Append,

    /// Should be used only when you want to replace the first occurrence.
    /// Use only for specific, targeted replacements where you need to modify
    /// just the first match.
    Replace,

    /// Should be used for renaming variables, functions, types, or any
    /// widespread replacements across the file. This is the recommended
    /// choice for consistent refactoring operations as it ensures all
    /// occurrences are updated.
    ReplaceAll,

    /// Swap the matched text with another text (search for the second text and
    /// swap them)
    Swap,
}

/// Helper trait to generate simple string enum schemas for unit enums.
///
/// This trait is automatically implemented for enums that derive both
/// `AsRefStr` and `EnumIter`. It provides a consistent way to generate
/// JSON schemas that represent enums as simple string enumerations
/// rather than complex oneOf structures.
trait SimpleEnumSchema: AsRef<str> + IntoEnumIterator {
    fn simple_enum_schema_name() -> Cow<'static, str> {
        std::any::type_name::<Self>()
            .split("::")
            .last()
            .unwrap_or("Enum")
            .to_string()
            .into()
    }

    fn simple_enum_schema(_gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        use schemars::json_schema;
        let variants: Vec<serde_json::Value> = Self::iter()
            .map(|variant| variant.as_ref().to_case(Case::Snake).into())
            .collect();

        json_schema!({
            "type": "string",
            "enum": variants
        })
    }
}

// Blanket implementation for all types that implement AsRef<str> and
// IntoEnumIterator
impl<T> SimpleEnumSchema for T where T: AsRef<str> + IntoEnumIterator {}

impl JsonSchema for PatchOperation {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

impl JsonSchema for OutputMode {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_patch.md"]
pub struct FSPatch {
    /// The absolute path to the file to modify
    #[serde(alias = "path")]
    pub file_path: String,

    /// The text to replace
    #[serde(alias = "search")]
    pub old_string: String,

    /// The text to replace it with (must be different from old_string)
    #[serde(alias = "content")]
    pub new_string: String,

    /// Replace all occurrences of old_string (default false)
    #[serde(default)]
    #[schemars(default)]
    pub replace_all: bool,
}

/// A single edit operation in a multi-patch
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct PatchEdit {
    /// The text to replace
    pub old_string: String,

    /// The text to replace it with (must be different from old_string)
    pub new_string: String,

    /// Replace all occurrences of old_string (default false)
    #[serde(default)]
    #[schemars(default)]
    pub replace_all: bool,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_multi_patch.md"]
pub struct FSMultiPatch {
    /// The absolute path to the file to modify
    pub file_path: String,

    /// Array of edit operations to perform sequentially on the file
    pub edits: Vec<PatchEdit>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_undo.md"]
pub struct FSUndo {
    /// The absolute path of the file to revert to its previous state.
    pub path: String,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/shell.md"]
pub struct Shell {
    /// The shell command to execute.
    pub command: String,

    /// The working directory where the command should be executed.
    /// If not specified, defaults to the current working directory from the
    /// environment.
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cwd: Option<PathBuf>,

    /// Whether to preserve ANSI escape codes in the output.
    /// If true, ANSI escape codes will be preserved in the output.
    /// If false (default), ANSI escape codes will be stripped from the output.
    #[serde(default)]
    #[serde(skip_serializing_if = "is_default")]
    pub keep_ansi: bool,

    /// Environment variable names to pass to command execution (e.g., ["PATH",
    /// "HOME", "USER"]). The system automatically reads the specified
    /// values and applies them during command execution.
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<String>>,

    /// Clear, concise description of what this command does. Recommended to be
    /// 5-10 words for simple commands. For complex commands with pipes or
    /// multiple operations, provide more context. Examples: "Lists files in
    /// current directory", "Installs package dependencies", "Compiles Rust
    /// project with release optimizations".
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Input type for the net fetch tool
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/net_fetch.md"]
pub struct NetFetch {
    /// URL to fetch
    pub url: String,

    /// Get raw content without any markdown conversion (default: false)
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw: Option<bool>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/followup.md"]
pub struct Followup {
    /// Question to ask the user
    pub question: String,

    /// If true, allows selecting multiple options; if false (default), only one
    /// option can be selected
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multiple: Option<bool>,

    /// First option to choose from
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option1: Option<String>,

    /// Second option to choose from
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option2: Option<String>,

    /// Third option to choose from
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option3: Option<String>,

    /// Fourth option to choose from
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option4: Option<String>,

    /// Fifth option to choose from
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option5: Option<String>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/plan_create.md"]
pub struct PlanCreate {
    /// The name of the plan (will be used in the filename)
    pub plan_name: String,

    /// The version of the plan (e.g., "v1", "v2", "1.0")
    pub version: String,

    /// The content to write to the plan file. This should be the complete
    /// plan content in markdown format.
    pub content: String,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/skill_fetch.md"]
pub struct SkillFetch {
    /// The name of the skill to fetch (e.g., "pdf", "code_review")
    pub name: String,
}

/// A single todo item sent by the model.
///
/// The model always provides `content` and `status`. The server uses `content`
/// as the key: if an item with the same content already exists it is updated,
/// otherwise a new item is added. Setting `status` to `cancelled` removes the
/// item from the list entirely. IDs are managed by the server and never
/// exposed to the model.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct TodoItem {
    /// Description of the task. Used as the unique key to match existing todos.
    pub content: String,
    /// Current status of the task. Use `cancelled` to remove the item.
    pub status: crate::TodoStatus,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/todo_write.md"]
pub struct TodoWrite {
    /// List of todo items to create or update. Each item must have `content`
    /// and `status`. The server matches on `content` — if an item with the
    /// same content exists it is updated; otherwise a new item is added.
    /// Set `status` to `cancelled` to remove an item.
    #[eserde(compat)]
    pub todos: Vec<TodoItem>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/todo_read.md"]
pub struct TodoRead {}

fn default_raw() -> Option<bool> {
    Some(false)
}

/// Retrieves content from URLs as markdown or raw text. Enables access to
/// current online information including websites, APIs and documentation. Use
/// for obtaining up-to-date information beyond training data, verifying facts,
/// or retrieving specific online content. Handles HTTP/HTTPS and converts HTML
/// to readable markdown by default. Cannot access private/restricted resources
/// requiring authentication. Respects robots.txt and may be blocked by
/// anti-scraping measures. For large pages, returns the first 40,000 characters
/// and stores the complete content in a temporary file for subsequent access.
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FetchInput {
    /// URL to fetch
    pub url: String,
    /// Get raw content without any markdown conversion (default: false)
    #[serde(default = "default_raw")]
    pub raw: Option<bool>,
}
/// Request to list files and directories within the specified directory. If
/// recursive is true, it will list all files and directories recursively. If
/// recursive is false or not provided, it will only list the top-level
/// contents. The path must be absolute. Do not use this tool to confirm the
/// existence of files you may have created, as the user will let you know if
/// the files were created successfully or not.
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FSListInput {
    /// The path of the directory to list contents for (absolute path required)
    pub path: String,
    /// Whether to list files recursively. Use true for recursive listing, false
    /// or omit for top-level only.
    pub recursive: Option<bool>,
}

/// Request to retrieve detailed metadata about a file or directory at the
/// specified path. Returns comprehensive information including size, creation
/// time, last modified time, permissions, and type. Path must be absolute. Use
/// this when you need to understand file characteristics without reading the
/// actual content.
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FSFileInfoInput {
    /// The path of the file or directory to inspect (absolute path required)
    pub path: String,
}

#[derive(Deserialize, JsonSchema)]
pub struct UndoInput {
    /// The absolute path of the file to revert to its previous state. Must be
    /// the exact path that was previously modified, created, or deleted by
    /// a Forge file operation. If the file was deleted, provide the
    /// original path it had before deletion. The system requires a prior
    /// snapshot for this path.
    pub path: String,
}

/// Input for the select tool
#[derive(Deserialize, JsonSchema)]
pub struct SelectInput {
    /// Question to ask the user
    pub question: String,

    /// First option to choose from
    pub option1: Option<String>,

    /// Second option to choose from
    pub option2: Option<String>,

    /// Third option to choose from
    pub option3: Option<String>,

    /// Fourth option to choose from
    pub option4: Option<String>,

    /// Fifth option to choose from
    pub option5: Option<String>,

    /// If true, allows selecting multiple options; if false (default), only one
    /// option can be selected
    #[schemars(default)]
    pub multiple: Option<bool>,
}

/// Helper function to check if a value equals its default value
fn is_default<T: Default + PartialEq>(t: &T) -> bool {
    t == &T::default()
}

impl ToolDescription for ToolCatalog {
    fn description(&self) -> String {
        match self {
            ToolCatalog::Patch(v) => v.description(),
            ToolCatalog::MultiPatch(v) => v.description(),
            ToolCatalog::Shell(v) => v.description(),
            ToolCatalog::Followup(v) => v.description(),
            ToolCatalog::Fetch(v) => v.description(),
            ToolCatalog::FsSearch(v) => v.description(),
            ToolCatalog::SemSearch(v) => v.description(),
            ToolCatalog::Read(v) => v.description(),
            ToolCatalog::Remove(v) => v.description(),
            ToolCatalog::Undo(v) => v.description(),
            ToolCatalog::Write(v) => v.description(),
            ToolCatalog::Plan(v) => v.description(),
            ToolCatalog::Skill(v) => v.description(),
            ToolCatalog::TodoWrite(v) => v.description(),
            ToolCatalog::TodoRead(v) => v.description(),
            ToolCatalog::Task(v) => v.description(),
        }
    }
}
// Cache of all tool names
static FORGE_TOOLS: LazyLock<HashSet<ToolName>> =
    LazyLock::new(|| ToolCatalog::iter().map(ToolName::new).collect());

// Case-insensitive lookup map: lowercase tool name -> canonical tool name
static FORGE_TOOLS_LOWER: LazyLock<HashMap<String, ToolName>> = LazyLock::new(|| {
    ToolCatalog::iter()
        .map(|tool| {
            let name = ToolName::new(tool.to_string());
            (name.as_str().to_lowercase(), name)
        })
        .collect()
});

/// Normalizes a tool name received in a response before catalog matching.
/// Trims surrounding whitespace and performs a case-insensitive lookup
/// against all known catalog tool names, returning the canonical form when
/// a match is found.
fn normalize_tool_name(name: &ToolName) -> ToolName {
    let trimmed = name.as_str().trim();
    let lower = trimmed.to_lowercase();
    FORGE_TOOLS_LOWER
        .get(&lower)
        .cloned()
        .unwrap_or_else(|| ToolName::new(trimmed))
}

impl ToolCatalog {
    pub fn schema(&self) -> Schema {
        use schemars::generate::SchemaSettings;
        use schemars::transform::{AddNullable, Transform};

        let r#gen = SchemaSettings::default()
            .with(|s| {
                s.meta_schema = None;
                s.inline_subschemas = true;
                s.transforms.push(Box::new(crate::RemoveSchemaTitles));
            })
            .into_generator();

        let mut schema = match self {
            ToolCatalog::Patch(_) => r#gen.into_root_schema_for::<FSPatch>(),
            ToolCatalog::MultiPatch(_) => r#gen.into_root_schema_for::<FSMultiPatch>(),
            ToolCatalog::Shell(_) => r#gen.into_root_schema_for::<Shell>(),
            ToolCatalog::Followup(_) => r#gen.into_root_schema_for::<Followup>(),
            ToolCatalog::Fetch(_) => r#gen.into_root_schema_for::<NetFetch>(),
            ToolCatalog::FsSearch(_) => r#gen.into_root_schema_for::<FSSearch>(),
            ToolCatalog::SemSearch(_) => r#gen.into_root_schema_for::<SemanticSearch>(),
            ToolCatalog::Read(_) => r#gen.into_root_schema_for::<FSRead>(),
            ToolCatalog::Remove(_) => r#gen.into_root_schema_for::<FSRemove>(),
            ToolCatalog::Undo(_) => r#gen.into_root_schema_for::<FSUndo>(),
            ToolCatalog::Write(_) => r#gen.into_root_schema_for::<FSWrite>(),
            ToolCatalog::Plan(_) => r#gen.into_root_schema_for::<PlanCreate>(),
            ToolCatalog::Skill(_) => r#gen.into_root_schema_for::<SkillFetch>(),
            ToolCatalog::Task(_) => r#gen.into_root_schema_for::<TaskInput>(),
            ToolCatalog::TodoWrite(_) => r#gen.into_root_schema_for::<TodoWrite>(),
            ToolCatalog::TodoRead(_) => r#gen.into_root_schema_for::<TodoRead>(),
        };

        // Apply transform to add nullable property and remove null from type
        AddNullable::default().transform(&mut schema);

        schema
    }

    pub fn definition(&self) -> ToolDefinition {
        ToolDefinition::new(self)
            .description(self.description())
            .input_schema(self.schema())
    }
    pub fn contains(tool_name: &ToolName) -> bool {
        let normalized = normalize_tool_name(tool_name);
        FORGE_TOOLS.contains(&normalized)
    }
    pub fn should_yield(tool_name: &ToolName) -> bool {
        // Tools that convey that the execution should yield
        let normalized = normalize_tool_name(tool_name);
        [ToolKind::Followup]
            .iter()
            .any(|v| v.to_string().to_case(Case::Snake).eq(normalized.as_str()))
    }

    pub fn requires_stdout(tool_name: &ToolName) -> bool {
        // Tools that require direct stdout/stderr access
        let normalized = normalize_tool_name(tool_name);
        [ToolKind::Shell]
            .iter()
            .any(|v| v.to_string().to_case(Case::Snake).eq(normalized.as_str()))
    }

    /// Convert a tool input to its corresponding domain operation for policy
    /// checking. Returns None for tools that don't require permission
    /// checks.
    pub fn to_policy_operation(
        &self,
        cwd: PathBuf,
    ) -> Option<crate::policies::PermissionOperation> {
        let cwd_path = cwd.clone();
        let display_path_for = |path: &str| {
            format!(
                "`{}`",
                format_display_path(Path::new(path), cwd_path.as_path())
            )
        };

        match self {
            ToolCatalog::Read(input) => Some(crate::policies::PermissionOperation::Read {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!("Read file: {}", display_path_for(&input.file_path)),
            }),
            ToolCatalog::Write(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!(
                    "Create/overwrite file: {}",
                    display_path_for(&input.file_path)
                ),
            }),
            ToolCatalog::FsSearch(input) => {
                let path_str = input.path.as_deref().unwrap_or(".");
                let base_message =
                    format!("Search in directory/file: {}", display_path_for(path_str));
                let message = match (&input.glob, &input.file_type) {
                    (Some(glob), _) => {
                        format!(
                            "{base_message} for pattern: '{}' in '{glob}' files",
                            input.pattern
                        )
                    }
                    (None, Some(file_type)) => {
                        format!(
                            "{base_message} for pattern: '{}' in {file_type} files",
                            input.pattern
                        )
                    }
                    (None, None) => {
                        format!("{base_message} for pattern: {}", input.pattern)
                    }
                };
                Some(crate::policies::PermissionOperation::Read {
                    path: std::path::PathBuf::from(path_str),
                    cwd,
                    message,
                })
            }
            ToolCatalog::Remove(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.path),
                cwd,
                message: format!("Remove file: {}", display_path_for(&input.path)),
            }),
            ToolCatalog::Patch(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!("Modify file: {}", display_path_for(&input.file_path)),
            }),
            ToolCatalog::MultiPatch(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!(
                    "Modify file with {} edits: {}",
                    input.edits.len(),
                    display_path_for(&input.file_path)
                ),
            }),
            ToolCatalog::Shell(input) => Some(crate::policies::PermissionOperation::Execute {
                command: input.command.clone(),
                cwd,
            }),
            ToolCatalog::Fetch(input) => Some(crate::policies::PermissionOperation::Fetch {
                url: input.url.clone(),
                cwd,
                message: format!("Fetch content from URL: {}", input.url),
            }),
            // Operations that don't require permission checks
            ToolCatalog::SemSearch(_)
            | ToolCatalog::Undo(_)
            | ToolCatalog::Followup(_)
            | ToolCatalog::Plan(_)
            | ToolCatalog::Skill(_)
            | ToolCatalog::TodoWrite(_)
            | ToolCatalog::TodoRead(_)
            | ToolCatalog::Task(_) => None,
        }
    }

    /// Creates a Read tool call with the specified path
    pub fn tool_call_read(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Read(FSRead {
            file_path: path.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Write tool call with the specified path and content
    pub fn tool_call_write(path: &str, content: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Write(FSWrite {
            file_path: path.to_string(),
            content: content.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Patch tool call with the specified parameters
    pub fn tool_call_patch(
        path: &str,
        content: &str,
        search: &str,
        replace_all: bool,
    ) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Patch(FSPatch {
            file_path: path.to_string(),
            old_string: search.to_string(),
            new_string: content.to_string(),
            replace_all,
        }))
    }

    /// Creates a Remove tool call with the specified path
    pub fn tool_call_remove(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Remove(FSRemove { path: path.to_string() }))
    }

    /// Creates a Shell tool call with the specified command and working
    /// directory
    pub fn tool_call_shell(command: &str, cwd: impl Into<PathBuf>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Shell(Shell {
            command: command.to_string(),
            cwd: Some(cwd.into()),
            ..Default::default()
        }))
    }

    /// Creates a Search tool call with the specified path and pattern
    pub fn tool_call_search(path: &str, pattern: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::FsSearch(FSSearch {
            pattern: pattern.to_string(),
            path: Some(path.to_string()),
            ..Default::default()
        }))
    }

    /// Creates a Semantic Search tool call with the specified queries
    pub fn tool_call_semantic_search(queries: Vec<SearchQuery>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::SemSearch(SemanticSearch { queries }))
    }

    /// Creates an Undo tool call with the specified path
    pub fn tool_call_undo(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Undo(FSUndo { path: path.to_string() }))
    }

    /// Creates a Fetch tool call with the specified url
    pub fn tool_call_fetch(url: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Fetch(NetFetch {
            url: url.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Followup tool call with the specified question
    pub fn tool_call_followup(question: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Followup(Followup {
            question: question.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Plan tool call with the specified plan name, version, and
    /// content
    pub fn tool_call_plan(plan_name: &str, version: &str, content: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Plan(PlanCreate {
            plan_name: plan_name.to_string(),
            version: version.to_string(),
            content: content.to_string(),
        }))
    }

    /// Creates a Skill tool call with the specified skill name
    pub fn tool_call_skill(skill_name: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Skill(SkillFetch {
            name: skill_name.to_string(),
        }))
    }

    /// Creates a TodoWrite tool call with the specified todo items
    pub fn tool_call_todo_write(todos: Vec<crate::TodoItem>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::TodoWrite(TodoWrite { todos }))
    }

    /// Creates a TodoRead tool call
    pub fn tool_call_todo_read() -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::TodoRead(TodoRead::default()))
    }

    /// Identifies the kind of the built-in Tools
    pub fn kind(&self) -> ToolKind {
        self.clone().into()
    }
}

fn format_display_path(path: &Path, cwd: &Path) -> String {
    // Try to create a relative path for display if possible
    let display_path = if path.starts_with(cwd) {
        match path.strip_prefix(cwd) {
            Ok(rel_path) => rel_path.display().to_string(),
            Err(_) => path.display().to_string(),
        }
    } else {
        path.display().to_string()
    };

    if display_path.is_empty() {
        ".".to_string()
    } else {
        display_path
    }
}

impl TryFrom<ToolCallFull> for ToolCatalog {
    type Error = crate::Error;

    fn try_from(value: ToolCallFull) -> Result<Self, Self::Error> {
        // Normalize the tool name: trim whitespace and perform case-insensitive
        // catalog match so the serde deserialization receives the canonical name.
        let normalized_name = normalize_tool_name(&value.name);

        let mut map = Map::new();
        map.insert("name".into(), normalized_name.as_str().into());

        // Parse the arguments
        let parsed_args = value.arguments.parse()?;

        // Try to find the tool definition and coerce types based on schema
        let coerced_args = ToolCatalog::iter()
            .find(|tool| tool.definition().name == normalized_name)
            .map(|tool| {
                let schema = tool.definition().input_schema;
                forge_json_repair::coerce_to_schema(parsed_args.clone(), &schema)
            })
            .unwrap_or(parsed_args);

        map.insert("arguments".into(), coerced_args);

        serde_json::from_value(serde_json::Value::Object(map))
            .map_err(|error| crate::Error::AgentCallArgument { error })
    }
}

impl ToolKind {
    pub fn name(&self) -> ToolName {
        ToolName::new(self.to_string().to_case(Case::Snake))
    }

    // TODO: This is an extremely slow operation
    pub fn definition(&self) -> ToolDefinition {
        ToolCatalog::iter()
            .find(|tool| tool.definition().name == self.name())
            .map(|tool| tool.definition())
            .expect("Forge tool definition not found")
    }
}

impl TryFrom<&ToolCallFull> for AgentInput {
    type Error = crate::Error;
    fn try_from(value: &ToolCallFull) -> Result<Self, Self::Error> {
        let value = value.arguments.parse()?;
        serde_json::from_value(value).map_err(|error| crate::Error::AgentCallArgument { error })
    }
}

impl From<ToolCatalog> for ToolCallFull {
    fn from(tool: ToolCatalog) -> Self {
        let name = ToolName::new(tool.to_string());
        // Serialize the tool to get the tagged enum structure
        let value = serde_json::to_value(&tool).expect("Failed to serialize tool");

        // Extract just the "arguments" part from the tagged enum
        let arguments = if let Some(args) = value.get("arguments") {
            ToolCallArguments::from(args.clone())
        } else {
            ToolCallArguments::default()
        };

        ToolCallFull { name, call_id: None, arguments, thought_signature: None }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use pretty_assertions::assert_eq;
    use strum::IntoEnumIterator;

    use super::Shell;
    use crate::{ToolCatalog, ToolKind, ToolName};

    #[test]
    fn test_tool_definition() {
        let actual = ToolKind::Remove.name();
        let expected = ToolName::new("remove");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_requires_stdout_for_shell() {
        let fixture = ToolName::new("shell");
        assert!(ToolCatalog::requires_stdout(&fixture));
    }

    #[test]
    fn test_requires_stdout_for_non_shell() {
        let fixture = ToolName::new("read");
        assert!(!ToolCatalog::requires_stdout(&fixture));
    }

    #[test]
    fn test_tool_definition_json() {
        let tools = ToolCatalog::iter()
            .map(|tool| {
                let definition = tool.definition().input_schema;
                serde_json::to_string_pretty(&definition)
                    .expect("Failed to serialize tool definition to JSON")
            })
            .collect::<Vec<_>>()
            .join("\n");

        insta::assert_snapshot!(tools);
    }

    #[test]
    fn test_coerce_string_integers_to_i32() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Simulate the exact error case: read tool with string integers instead of i32
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        // This should not panic - it should coerce strings to integers
        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse with coerced types"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_coerce_preserves_correct_types() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Verify that already-correct types are preserved
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse with correct types"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_capitalized_read_alias() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test that "Read" (capitalized) is normalized to "read"
        let tool_call = ToolCallFull {
            name: ToolName::new("Read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse capitalized 'Read' tool name"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_capitalized_write_alias() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test that "Write" (capitalized) is normalized to "write"
        let tool_call = ToolCallFull {
            name: ToolName::new("Write"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "content": "test content"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse capitalized 'Write' tool name"
        );

        if let Ok(ToolCatalog::Write(fs_write)) = actual {
            assert_eq!(fs_write.file_path, "/test/path.rs");
            assert_eq!(fs_write.content, "test content");
        } else {
            panic!("Expected FSWrite variant");
        }
    }

    #[test]
    fn test_lowercase_read_still_works() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Ensure lowercase still works (backward compatibility)
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(r#"{"path": "/test/path.rs"}"#),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse lowercase 'read' tool name"
        );

        matches!(actual.unwrap(), ToolCatalog::Read(_));
    }

    #[test]
    fn test_lowercase_write_still_works() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Ensure lowercase still works (backward compatibility)
        let tool_call = ToolCallFull {
            name: ToolName::new("write"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "content": "test"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse lowercase 'write' tool name"
        );

        matches!(actual.unwrap(), ToolCatalog::Write(_));
    }

    #[test]
    fn test_contains_with_lowercase() {
        assert!(ToolCatalog::contains(&ToolName::new("read")));
        assert!(ToolCatalog::contains(&ToolName::new("write")));
        assert!(!ToolCatalog::contains(&ToolName::new("nonexistent")));
    }

    #[test]
    fn test_contains_with_capitalized() {
        // Test that capitalized versions are also found
        assert!(
            ToolCatalog::contains(&ToolName::new("Read")),
            "Should contain capitalized 'Read'"
        );
        assert!(
            ToolCatalog::contains(&ToolName::new("Write")),
            "Should contain capitalized 'Write'"
        );
    }

    #[test]
    fn test_fs_search_message_with_regex() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_regex = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: "fn main".to_string(),
            ..Default::default()
        });

        let operation = search_with_regex
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: fn main"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_without_regex() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_without_regex = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: ".*".to_string(), // Match all content
            ..Default::default()
        });

        let operation = search_without_regex
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: .*"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_with_file_pattern_only() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_pattern = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: ".*".to_string(),
            glob: Some("*.rs".to_string()),
            ..Default::default()
        });

        let operation = search_with_pattern
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: '.*' in '*.rs' files"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_with_regex_and_file_pattern() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_both = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: "fn main".to_string(),
            glob: Some("*.rs".to_string()),
            ..Default::default()
        });

        let operation = search_with_both
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: 'fn main' in '*.rs' files"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_path() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "path" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/file.rs", "operation": "replace", "new_string": "new", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'path' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_search() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "search" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "new_string": "new", "search": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'search' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.old_string, "old text");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_content() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "content" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "content": "new content", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'content' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_all_old_fields() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test all old field names together
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/file.rs", "operation": "replace", "content": "new content", "search": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse all old field names together"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
            assert_eq!(fs_patch.old_string, "old text");
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_new_field_names() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test new field names work as expected
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "new_string": "new content", "old_string": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(actual.is_ok(), "Should successfully parse new field names");

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
            assert_eq!(fs_patch.old_string, "old text");
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_with_replace_all() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test replace_all parameter
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "new_string": "new", "old_string": "old", "replace_all": true}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse replace_all parameter"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.replace_all, true);
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_unit_enum_schema_generation() {
        use schemars::generate::SchemaSettings;

        use crate::{OutputMode, PatchOperation};

        // Test PatchOperation schema
        let settings = SchemaSettings::default().into_generator();
        let patch_schema = settings.into_root_schema_for::<PatchOperation>();

        // In schemars 1.0, Schema wraps serde_json::Value, so we check the JSON
        // directly
        let schema_value = patch_schema.as_value();
        assert_eq!(schema_value.get("type"), Some(&serde_json::json!("string")));

        let enum_values = schema_value.get("enum").and_then(|v| v.as_array()).unwrap();
        assert_eq!(enum_values.len(), 5);
        assert_eq!(enum_values[0], serde_json::json!("prepend"));
        assert_eq!(enum_values[1], serde_json::json!("append"));

        // Test OutputMode schema
        let settings = SchemaSettings::default().into_generator();
        let output_schema = settings.into_root_schema_for::<OutputMode>();

        // Verify it also generates a simple string enum
        let schema_value = output_schema.as_value();
        assert_eq!(schema_value.get("type"), Some(&serde_json::json!("string")));

        let enum_values = schema_value.get("enum").and_then(|v| v.as_array()).unwrap();
        assert_eq!(enum_values.len(), 3);
        assert_eq!(enum_values[0], serde_json::json!("content"));
        assert_eq!(enum_values[1], serde_json::json!("files_with_matches"));
        assert_eq!(enum_values[2], serde_json::json!("count"));
    }

    #[test]
    fn test_shell_with_description_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "git status".to_string(),
            cwd: Some(PathBuf::from("/test")),
            keep_ansi: false,
            env: None,
            description: Some("Shows working tree status".to_string()),
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "git status",
            "cwd": "/test",
            "description": "Shows working tree status"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_shell_without_description_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "ls -la".to_string(),
            cwd: Some(PathBuf::from("/home")),
            keep_ansi: false,
            env: None,
            description: None,
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "ls -la",
            "cwd": "/home"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_shell_without_cwd_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "pwd".to_string(),
            cwd: None,
            keep_ansi: false,
            env: None,
            description: None,
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "pwd"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_trims_whitespace() {
        let actual = super::normalize_tool_name(&ToolName::new("  read  "));
        let expected = ToolName::new("read");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_case_insensitive_uppercase() {
        let actual = super::normalize_tool_name(&ToolName::new("READ"));
        let expected = ToolName::new("read");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_case_insensitive_mixed() {
        let actual = super::normalize_tool_name(&ToolName::new("FS_SEARCH"));
        let expected = ToolName::new("fs_search");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_trim_and_case_insensitive() {
        let actual = super::normalize_tool_name(&ToolName::new("  SHELL  "));
        let expected = ToolName::new("shell");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_unknown_returns_trimmed() {
        let actual = super::normalize_tool_name(&ToolName::new("  unknown_tool  "));
        let expected = ToolName::new("unknown_tool");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_contains_case_insensitive() {
        assert!(ToolCatalog::contains(&ToolName::new("READ")));
        assert!(ToolCatalog::contains(&ToolName::new("Shell")));
        assert!(ToolCatalog::contains(&ToolName::new("PATCH")));
        assert!(!ToolCatalog::contains(&ToolName::new("nonexistent")));
    }

    #[test]
    fn test_contains_with_whitespace() {
        assert!(ToolCatalog::contains(&ToolName::new("  read  ")));
        assert!(ToolCatalog::contains(&ToolName::new(" shell ")));
    }

    #[test]
    fn test_try_from_tool_call_uppercase_name() {
        use crate::{ToolCallArguments, ToolCallFull};

        let tool_call = ToolCallFull {
            name: ToolName::new("SHELL"),
            call_id: None,
            arguments: ToolCallArguments::from_json(r#"{"command": "ls"}"#),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(actual.is_ok(), "Should parse uppercase 'SHELL' tool name");
        assert!(matches!(actual.unwrap(), ToolCatalog::Shell(_)));
    }

    #[test]
    fn test_try_from_tool_call_with_whitespace_name() {
        use crate::{ToolCallArguments, ToolCallFull};

        let tool_call = ToolCallFull {
            name: ToolName::new("  patch  "),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "new_string": "new", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should parse whitespace-padded 'patch' tool name"
        );
        assert!(matches!(actual.unwrap(), ToolCatalog::Patch(_)));
    }
}
